title: Lightcodepedia
description: A GitHub Pages site
defaults:
  - scope:
      path: ""   # applies to all files
    values:
      title: "💡lightcodepedia"
exclude:
  - modules/**
plugins:
  - jekyll-last-modified-at
