title: Lightcodepedia
description: A GitHub Pages site

defaults:
  - scope:
      path: ""   # all files
    values:
      title: "💡lightcodepedia"
  - scope:
      path: "modules"   # only /modules
    values:
      layout: null      # don’t wrap them in HTML

# Important: tell Jekyll to copy .yaml as-is
include:
  - modules
  - modules/*.yaml
